<script type="text/javascript">
    var back = function() {
        window.location = '';
    }
</script>

<div class="key-form">
    <h3 class="info-message info-large">
        GiftFox is a <a>steamgifts.com</a> bot for the lazy lottery participants among us.
        The bot is using your steamgifts session in order to automatically join available
        giveaways for you, based on your settings and notify you via e-mail once you win
        something.
    </h3>
    <h3 class="info-message info-large" style="text-align:center;">
        <br /><img src="/giftfox/public/appimage.png" alt=""/><br />
    </h3>
    <h3 class="info-message info-large">
        Due to the fact that the bot is doing everything on its own and is therefore impacting
        the win chance of any participant, its run interval is set to a reasonable time. Also,
        since this basically takes all the 'work' of joining giveaways from you, we ask you to
        also create giveaways from time to time.<br /><br />
        In the end, using a bot to join giveaways is allowed and can hardly be detected, depending
        on how you do it. GiftFox provides you an easy way to auto-join giveaways but also asks
        you to contribute to the site in exchange. <strong>-- tl;dr Don't be an asshole</strong> c:
    </h3>
    <h3 class="info-message info-large" style="text-align:center;">
        <br /><img src="/giftfox/public/appimage.png" alt=""/><br />
    </h3>
    <h3 class="info-message info-large">
        Using the bot is pretty simple. Just <a>create an account</a> and log in with your
        account information. GiftFox does not use your actual Steam account data but instead
        your steamgifts session id. The session id is a random string generated by the server
        when you log in to <a>steamgifts.com</a>. Copying it is a bit tricky but it's the safest
        way for you to allow this bot to perform actions with your account without actually
        providing any sensitive information such as your steam login.<br /><br />
        Once you log in to your account, GifFox will prompt you to enter your session id and gives
        you some information on how to retrieve it. After that, you will be redirected to the
        actual user interface and the bot will do everything on its own from that point on.<br /><br />
        Here's a sneak peak on what the actual bot interface looks like:
    </h3>
    <h3 class="info-message info-large" style="text-align: center;">
        <img class="info-image" src="/giftfox/public/apppreview.png" alt=""/><br />
    </h3>
    <h3 class="info-message info-large" style="text-align:center;">
        <br /><img src="/giftfox/public/appimage.png" alt=""/><br />
    </h3>
    <h3 class="info-message info-large">
        To increase the efficiency of the bot, please hide giveaways that you can't enter anyways in
        your <a href="http://www.steamgifts.com/account/settings/giveaways">Giveaway settings</a>.
        (Set everything to "Yes")
    </h3>
    <h3 class="info-message info-large">
        If you run into any bugs, problems or anything you want to talk about, shoot me a mail to
        <a href="mailto:cbrxde@gmail.com">cbrxde@gmail.com</a> or shoot me a tweet to
        <a href="https://twitter.com/cybroxde">@cybroxde</a>.
    </h3>
    <h3 class="info-message info-small">
        Code and design by cybrox, icon by 4DAMANT
    </h3>
</div>